Update to wasi-sdk-16
fastly/js-compute-runtime pull request #337
Opened 2022-12-08 17:26 UTC by elliottt

As wasi-sdk-16 uses a version of llvm that runs wasm-opt on its output if it's available in `$PATH`, we need to enable the wizer flag for handling bulk memory. Luckily the bulk memory uses are limited to `memory.copy`, which wizer supports well.

2022-12-08 17:52 UTC, JakeChampion requested changes
Seeing issues in CI about invalid wasm:
https://github.com/fastly/js-compute-runtime/actions/runs/3650612649/jobs/6167084453

> ERROR: the Fastly API returned 400 Bad Request: Bad request (ERROR: failed to parse WebAssembly module
> 
> Caused by:
>     Invalid input WebAssembly code at offset 6718101: data count and data section have inconsistent lengths).

I'm not sure what would cause this

2022-12-08 18:01 UTC, elliottt commented
Let's close this for now. Using wasi-sdk 15 is fine for now, and my guess is that this is related to llvm running `wasm-opt` with options that we have no control over.

2022-12-08 18:42 UTC, elliottt commented
After shadowing `wasm-opt` in the path in 321f4f0da482591fcb88b7787dd6fd07a34a89e8, the problems persist. Additionally, it turns out that clang is adding the bulk memory operations, not `wasm-opt`.

2022-12-09 18:24 UTC, JakeChampion approved these changes

2022-12-09 18:27 UTC, merged